<a href="https://colab.research.google.com/github/pawantilara/Hello-World/blob/master/Untitled29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
d=pd.read_csv("https://raw.githubusercontent.com/datasets/hepatitis/master/data/hepatitis.csv")

In [4]:
d.shape

(155, 20)

In [5]:
d.head(10)

age     sex steroid  antivirals fatigue malaise anorexia liver_big  \
0   30    male   False       False   False   False    False     False   
1   50  female   False       False    True   False    False     False   
2   78  female    True       False    True   False    False      True   
3   31  female     NaN        True   False   False    False      True   
4   34  female    True       False   False   False    False      True   
5   34  female    True       False   False   False    False      True   
6   51  female   False       False    True   False     True      True   
7   23  female    True       False   False   False    False      True   
8   39  female    True       False    True   False    False      True   
9   30  female    True       False   False   False    False      True   

  liver_firm spleen_palpable spiders ascites varices  bilirubin  \
0      False           False   False   False   False        1.0   
1      False           False   False   False   False        0.9   
2      False           False   False   False   False        0.7   
3      False           False   False   False   False        0.7   
4      False           False   False   False   False        1.0   
5      False           False   False   False   False        0.9   
6      False            True    True   False   False        NaN   
7      False           False   False   False   False        1.0   
8       True           False   False   False   False        0.7   
9      False           False   False   False   False        1.0   

   alk_phosphate   sgot  albumin  protime  histology class  
0           85.0   18.0      4.0      NaN      False  live  
1          135.0   42.0      3.5      NaN      False  live  
2           96.0   32.0      4.0      NaN      False  live  
3           46.0   52.0      4.0     80.0      False  live  
4            NaN  200.0      4.0      NaN      False  live  
5           95.0   28.0      4.0     75.0      False  live  
6            NaN    NaN      NaN      NaN      False   die  
7            NaN    NaN      NaN      NaN      False  live  
8            NaN   48.0      4.4      NaN      False  live  
9            NaN  120.0      3.9      NaN      False  live

In [6]:
d.tail()

age     sex steroid  antivirals fatigue malaise anorexia liver_big  \
150   46  female    True       False    True    True     True      True   
151   44  female    True       False    True   False    False      True   
152   61  female   False       False    True    True    False     False   
153   53    male   False       False    True   False    False      True   
154   43  female    True       False    True   False    False      True   

    liver_firm spleen_palpable spiders ascites varices  bilirubin  \
150      False           False    True    True    True        7.6   
151       True           False   False   False   False        0.9   
152       True           False    True   False   False        0.8   
153      False            True    True   False    True        1.5   
154      False            True    True    True   False        1.2   

     alk_phosphate   sgot  albumin  protime  histology class  
150            NaN  242.0      3.3     50.0       True   die  
151          126.0  142.0      4.3      NaN       True  live  
152           75.0   20.0      4.1      NaN       True  live  
153           81.0   19.0      4.1     48.0       True  live  
154          100.0   19.0      3.1     42.0       True   die

In [7]:
d.describe()

age   bilirubin  alk_phosphate       sgot     albumin  \
count  155.000000  149.000000     126.000000  151.00000  139.000000   
mean    41.200000    1.427517     105.325397   85.89404    3.817266   
std     12.565878    1.212149      51.508109   89.65089    0.651523   
min      7.000000    0.300000      26.000000   14.00000    2.100000   
25%     32.000000    0.700000      74.250000   31.50000    3.400000   
50%     39.000000    1.000000      85.000000   58.00000    4.000000   
75%     50.000000    1.500000     132.250000  100.50000    4.200000   
max     78.000000    8.000000     295.000000  648.00000    6.400000   

          protime  
count   88.000000  
mean    61.852273  
std     22.875244  
min      0.000000  
25%     46.000000  
50%     61.000000  
75%     76.250000  
max    100.000000

In [8]:
d.describe().transpose()

count        mean        std   min    25%   50%     75%    max
age            155.0   41.200000  12.565878   7.0  32.00  39.0   50.00   78.0
bilirubin      149.0    1.427517   1.212149   0.3   0.70   1.0    1.50    8.0
alk_phosphate  126.0  105.325397  51.508109  26.0  74.25  85.0  132.25  295.0
sgot           151.0   85.894040  89.650890  14.0  31.50  58.0  100.50  648.0
albumin        139.0    3.817266   0.651523   2.1   3.40   4.0    4.20    6.4
protime         88.0   61.852273  22.875244   0.0  46.00  61.0   76.25  100.0

In [9]:
d.dtypes

age                  int64
sex                 object
steroid             object
antivirals            bool
fatigue             object
malaise             object
anorexia            object
liver_big           object
liver_firm          object
spleen_palpable     object
spiders             object
ascites             object
varices             object
bilirubin          float64
alk_phosphate      float64
sgot               float64
albumin            float64
protime            float64
histology             bool
class               object
dtype: object

# **Data Cleaning**

In [10]:
d.isnull().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [11]:
d['protime']=d.protime.fillna(d.protime.mean())

In [12]:
d['protime']=d['protime'].astype(int)

In [13]:
d['albumin']=d.albumin.fillna(d.albumin.mean())

In [14]:
d['albumin']=d['albumin'].astype(int)

In [15]:
d['sgot']=d.sgot.fillna(d.sgot.mean())
d['sgot']=d['sgot'].astype(int)

In [16]:
d['alk_phosphate']=d.alk_phosphate.fillna(d.alk_phosphate .mean())
d['alk_phosphate']=d['alk_phosphate'].astype(int)

In [17]:
d['bilirubin']=d.bilirubin.fillna(d.bilirubin.mean())
d['bilirubin']=d['bilirubin'].astype(int)

In [18]:
d.dtypes

age                 int64
sex                object
steroid            object
antivirals           bool
fatigue            object
malaise            object
anorexia           object
liver_big          object
liver_firm         object
spleen_palpable    object
spiders            object
ascites            object
varices            object
bilirubin           int32
alk_phosphate       int32
sgot                int32
albumin             int32
protime             int32
histology            bool
class              object
dtype: object

In [19]:
d.isnull().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           0
alk_phosphate       0
sgot                0
albumin             0
protime             0
histology           0
class               0
dtype: int64

In [20]:
d['liver_big']=d.liver_big.fillna(method='ffill')
# ffill mean forword fill...
# bfill mean backward fill...

In [21]:
d['liver_firm']=d.liver_firm.fillna(method='bfill')
d['spleen_palpable']=d.spleen_palpable.fillna(method='bfill')
d['spiders']=d.spiders.fillna(method='bfill')
d['ascites']=d.ascites.fillna(method='bfill')
d['varices']=d.varices.fillna(method='bfill')


In [22]:
d.isnull().sum()

age                0
sex                0
steroid            1
antivirals         0
fatigue            1
malaise            1
anorexia           1
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

In [23]:
d['steroid']=d.steroid.fillna(method='ffill')
d['fatigue']=d.fatigue.fillna(method='ffill')
d['malaise']=d.malaise.fillna(method='ffill')
d['anorexia']=d.anorexia.fillna(method='ffill')


In [24]:
d.isnull().sum()

age                0
sex                0
steroid            0
antivirals         0
fatigue            0
malaise            0
anorexia           0
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

In [25]:
X=d.replace('live',1)


In [26]:
df=X.replace('die',0)

In [27]:
X=df.replace('male',1)

In [28]:
df=X.replace('female',0)

In [54]:
df.head(2)

age  sex  bilirubin  alk_phosphate  sgot  albumin  protime  class
0   30    1          1             85    18        4       61      1
1   50    0          0            135    42        3       61      1

In [30]:
df=df.drop(columns=['steroid','antivirals','fatigue','malaise','anorexia','liver_firm','liver_big','spleen_palpable','spiders','ascites','varices','histology'])

In [55]:
df.head(2)

age  sex  bilirubin  alk_phosphate  sgot  albumin  protime  class
0   30    1          1             85    18        4       61      1
1   50    0          0            135    42        3       61      1

In [32]:
X = df.drop(columns=['class'])

In [33]:
y = df['class'].values

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)

## KNeighbors

In [35]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 10)

knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=10, p=2,
           weights='uniform')

In [53]:
y_pred=knn.predict(X_test)
print("Accuracy: ", accuracy_score(y_pred, y_test))

Accuracy:  0.8064516129032258


## SVM

In [51]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [52]:
sv = SVC(gamma='auto')
sv.fit(X_train,y_train)
y_pred = sv.predict(X_test)
print("Accuracy: ", accuracy_score(y_pred,y_test))

Accuracy:  0.8064516129032258


## Confusion matrix

In [39]:
y_test

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [40]:
x=np.array(y_pred)

In [41]:
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
cnf_matrix = confusion_matrix(y_test, y_pred)

In [44]:
cnf_matrix

array([[ 0,  6],
       [ 0, 25]], dtype=int64)